title: "Wi-Fi Access Points Database"
description: "Comprehensive database of Wi-Fi Access Point specifications"
url: "https://ap.networkjon.fr"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - convert_excel_to_yaml.py
  - update_database.sh
  - "*.xlsx"
  - "*.backup_*"

# GitHub Pages settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
